services:
  docker-hosts:
    image: ghcr.io/djsisson/docker-hosts:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hosts:/tmp/hosts:rw
